spring:
    cloud:
        stream:
            bindings:
                output:
                  destination: 'mayank'
            kafka:
              binder:
                brokers: localhost
                defaultBrokerPort: 9092
