server:
    port: 8081
spring:
    cloud:
        stream:
            bindings:
                input:
                    destination: 'mayank'

            kafka:
                binder:
                    brokers: localhost
                    defaultBrokerPort: 9092
